services:
  - type: web
    name: mhacks25
    env: python
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: FLASK_ENV
        value: production
      - key: TRUST_PROXY
        value: "1"
    headers:
      - path: /*
        name: Strict-Transport-Security
        value: max-age=31536000; includeSubDomains
